### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:postgres

### ISSUE THREAD

**Issue by ab7** [ab7/api-boilerplate#2]
```
$ docker-compose logs -f api
Attaching to api-boilerplate_api_1
api_1       | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
api_1       | INFO:     Started reloader process [8] using statreload
api_1       | Process SpawnProcess-1:
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
api_1       |     self.run()
api_1       |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
api_1       |     self._target(*self._args, **self._kwargs)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
api_1       |     target(sockets=sockets)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 390, in run
api_1       |     loop.run_until_complete(self.serve(sockets=sockets))
api_1       |   File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 397, in serve
api_1       |     config.load()
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/config.py", line 278, in load
api_1       |     self.loaded_app = import_from_string(self.app)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
api_1       |     module = importlib.import_module(module_str)
api_1       |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
api_1       |     return _bootstrap._gcd_import(name[level:], package, level)
api_1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
api_1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
api_1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
api_1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
api_1       |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
api_1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
api_1       |   File "./api/api.py", line 6, in <module>
api_1       |     from data import schemas, models
api_1       |   File "./data/models.py", line 3, in <module>
api_1       |     from .db import Base
api_1       |   File "./data/db.py", line 9, in <module>
api_1       |     engine = create_engine(SQLALCHEMY_DATABASE_URL)
api_1       |   File "<string>", line 2, in create_engine
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
api_1       |     entrypoint = u._get_entrypoint()
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 636, in _get_entrypoint
api_1       |     cls = registry.load(name)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
api_1       |     raise exc.NoSuchModuleError(
api_1       | sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
api_1       | INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
api_1       | INFO:     Started reloader process [8] using statreload
api_1       | Process SpawnProcess-1:
api_1       | Traceback (most recent call last):
api_1       |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
api_1       |     self.run()
api_1       |   File "/usr/local/lib/python3.9/multiprocessing/process.py", line 108, in run
api_1       |     self._target(*self._args, **self._kwargs)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/subprocess.py", line 62, in subprocess_started
api_1       |     target(sockets=sockets)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 390, in run
api_1       |     loop.run_until_complete(self.serve(sockets=sockets))
api_1       |   File "uvloop/loop.pyx", line 1494, in uvloop.loop.Loop.run_until_complete
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/main.py", line 397, in serve
api_1       |     config.load()
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/config.py", line 278, in load
api_1       |     self.loaded_app = import_from_string(self.app)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/uvicorn/importer.py", line 20, in import_from_string
api_1       |     module = importlib.import_module(module_str)
api_1       |   File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
api_1       |     return _bootstrap._gcd_import(name[level:], package, level)
api_1       |   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
api_1       |   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
api_1       |   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
api_1       |   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
api_1       |   File "<frozen importlib._bootstrap_external>", line 790, in exec_module
api_1       |   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
api_1       |   File "./api/api.py", line 6, in <module>
api_1       |     from data import schemas, models
api_1       |   File "./data/models.py", line 3, in <module>
api_1       |     from .db import Base
api_1       |   File "./data/db.py", line 9, in <module>
api_1       |     engine = create_engine(SQLALCHEMY_DATABASE_URL)
api_1       |   File "<string>", line 2, in create_engine
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
api_1       |     return fn(*args, **kwargs)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 522, in create_engine
api_1       |     entrypoint = u._get_entrypoint()
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/sqlalchemy/engine/url.py", line 636, in _get_entrypoint
api_1       |     cls = registry.load(name)
api_1       |   File "/root/.cache/pypoetry/virtualenvs/api-boilerplate-9TtSrW0h-py3.9/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
api_1       |     raise exc.NoSuchModuleError(
api_1       | sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
```

**Comment by ab7** [comment]
Looks like using `postgres://` is deprecated now. See https://stackoverflow.com/a/64698899.
